esphome:
  name: $devicename
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret WIFI_SSID
  password: !secret WIFI_PASSWORD
  fast_connect: false
  reboot_timeout: 5min
  power_save_mode: none
  manual_ip:
    static_ip: $static_ip
    gateway: 192.168.4.1
    subnet: 255.255.255.0
    dns1: 192.168.4.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ESP32 FH $devicename
    password: !secret FALLBACK_PASSWORD


mqtt:
  broker: !secret MQTT_BROKER
  password: !secret MQTT_PASSWORD
  username: !secret MQTT_USERNAME
  keepalive: 5s

captive_portal:

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: !secret API_PASSWORD

ota:
  password: !secret OTA_PASSWORD

uart:
  rx_pin: 17
  tx_pin: 16
  baud_rate: 9600

# MQTT Part feels hacky but needet for mqttgateway to work properly
sensor:
  - platform: mhz19
    co2:
      name: "CO2 Value"
      on_value:
        then:
          - mqtt.publish:
              topic: sensors/sensor/$devicename/co2
              payload: !lambda "return String(x).c_str();"
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 2
            send_first_at: 2
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 15s
    automatic_baseline_calibration: false
  - platform: dht
    model: DHT22
    pin: 4
    temperature:
      name: "Temperature"
      on_value:
        then:
          - mqtt.publish:
              topic: sensors/sensor/$devicename/temperature
              payload: !lambda "return String(x).c_str();"
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 2
            send_first_at: 2
    humidity:
      name: "Humidity"
      on_value:
        then:
          - mqtt.publish:
              topic: sensors/sensor/$devicename/humidity
              payload: !lambda "return String(x).c_str();"
      filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 2
          send_first_at: 2
    update_interval: 15s
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
